### ISSUE TITLE
Calculadora de coordenadas - DMS e precisão

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#11]
Gerar latitude e longitude em DMS.
Ajustar precisão das coordenadas (métricas e DMS).

**Comment by dinizime** [comment]
Verificar se ainda procede @JoaoFelipeAGuimaraes .

**Comment by JoaoFelipeAGuimaraes** [comment]
Ciente, ainda precisa ser mudado

**Comment by diegobenincasa** [comment]
Ajustado. Agora a ferramenta:

- Gera coordenadas métricas com 3 casas decimais e separador de milhar.
- Gera coordenadas DMS com símbolos de grau, minuto e segundo.
