### ISSUE TITLE
Localizar carta - Rubberband persiste ao fechar dock

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#12]
Rubberband de seleção por box não é removido ao fechar dock. Não há modo de excluí-lo posteriormente, nem fechando o QGIS caso o projeto seja salvo com este dummy rubberband.

**Comment by dinizime** [comment]
Verificar se ainda procede @JoaoFelipeAGuimaraes .

**Comment by JoaoFelipeAGuimaraes** [comment]
Nao ocorre na nova versão
