### ISSUE TITLE
Calculadora de coordenadas - Não cria sem LatLong

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#13]
Se o usuário não selecionar a opção LatLong, a ferramenta não cria nenhuma coordenada na tabela de atributos.

Corrigir.

**Comment by dinizime** [comment]
Verificar se ainda procede @JoaoFelipeAGuimaraes .

**Comment by JoaoFelipeAGuimaraes** [comment]
Não ocorre na nova versão
