### ISSUE TITLE
QGIS 3.x

### ISSUE THREAD

**Issue by leonardoms** [dsgoficial/DSGToolsOp#16]
Estou com problemas pra instalar no QGIS 3.4 (Madeira), alguma previsão de portar o DSGToolsOp para as versões mais novas do QGIS, assim como o DSGTools ?

**Comment by diegobenincasa** [comment]
Boa noite!

Estou em trabalho para fazer as adaptações necessárias, mas leva um certo
tempo. Não tenho uma previsão concreta para lhe dar, infelizmente. O que
posso dizer é que os esforços são para que o plugin esteja disponível nos
próximos meses.

Abraço!

Em seg, 16 de set de 2019 21:22, Leonardo Monteiro <notifications@github.com>
escreveu:

**Comment by leonardoms** [comment]
Entendo, tive dificuldades em tentar adaptar o código, alguns arquivos estão com uma espécie de marcação:
>>>>>HEADER
========
<<<<<<<<< 123456...

Isso vem da ferramenta que você esta usando?

**Comment by diegobenincasa** [comment]
Sim, eu já havia percebido isso. O plugin não é desenvolvido só por mim: a
ferramenta de Simbologia Militar é feita por um militar do RJ. E o problema
é que ele me repassou o código errado, com algumas marcações do Git que não
deveriam existir (essa >>>> HEAD é uma delas). Inclusive eu retirei a
última versão do plugin de lá do repositório oficial do QGIS, justamente
por conta disso.

Vou conversar com ele hoje pessoalmente, daí já ajusto essa questão. ;-)

Em seg, 16 de set de 2019 23:31, Leonardo Monteiro <notifications@github.com>
escreveu:

**Comment by leonardoms** [comment]
Isso seria ótimo!
Abraço.

**Comment by diegobenincasa** [comment]
Resolvido.
