### ISSUE TITLE
convergencia meridiana com sinal sempre negativo

### ISSUE THREAD

**Issue by JoaoFelipeAGuimaraes** [dsgoficial/DSGToolsOp#17]
no arquivo 'auxiliar.py' o cálculo da convergência meridiana não leva em conta a posição relativa ao fuso central, resultando em resultado sempre negativo para convergência.

basta trocar a linha 51:
       c = cSeconds/3600

por:
        if abs(longitude)<abs(centralMeridian):
                c = -cSeconds/3600
        else:
                c = cSeconds/3600

**Comment by diegobenincasa** [comment]
Bem observado. Vou modificar.

Obrigado pela contribuição!
