### ISSUE TITLE
Remover ou referenciar dependências externas

### ISSUE THREAD

**Issue by dinizime** [dsgoficial/DSGToolsOp#20]
Referenciar corretamente o código de terceiros ou remover a dependência externa completamente.

**Comment by diegobenincasa** [comment]
Sugestão: criar diálogo "Sobre o DSGTools Op" no menu "Ferramentas Militares", com a referência às bibliotecas de terceiros e aos plugins utilizados como base. Deve permitir trocar o idioma dos textos do diálogo para inglês, visto que tais bibliotecas/plugins são estrangeiros.

**BIBLIOTECAS**
- GeoPy - [https://pypi.org/project/geopy/](https://pypi.org/project/geopy/)
- GeographicLib - [https://pypi.org/project/geographiclib/](https://pypi.org/project/geographiclib/)
- Geomag - [https://pypi.org/project/geomag/](https://pypi.org/project/geomag/)

**PLUGINS**
- Numerical Digitize - [https://plugins.qgis.org/plugins/numericalDigitize/](https://plugins.qgis.org/plugins/numericalDigitize/)
- Numerical Vertex Edit - [https://plugins.qgis.org/plugins/numericalVertexEdit/](https://plugins.qgis.org/plugins/numericalVertexEdit/)
- Profile Tool - [https://plugins.qgis.org/plugins/profiletool/](https://plugins.qgis.org/plugins/profiletool/)

**Comment by dinizime** [comment]
Além de referenciar em Créditos no readme do Github, e comentar no código.

**Comment by JoaoFelipeAGuimaraes** [comment]
Código referenciado e readme atualizado com códigos externos incorporados
