### ISSUE TITLE
Incompatibilidade dos estilos QML do Simbologia Militar com QGIS 3

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#22]
Os estilos criados para o Simbologia Militar funcionam parcialmente. Os símbolos e regras carregam normalmente, mas as propriedades especiais (mapa de valores, atributo oculto, etc.) não. Aparentemente houve mudança no schema do QML, mas não há ferramentas para conversão disponíveis.

Deve-se exportar todos os mapas de valores com QGIS 2, reconfigurar todas as camadas no QGIS 3 com tais mapas, e exportar cada QML novamente, substituindo os atuais.

**Comment by JoaoFelipeAGuimaraes** [comment]
Simbologia funciona para versao 3.4, para 3.10 é necessário recriar os .qml no QGIS 3. 
Em trabalho

**Comment by diegobenincasa** [comment]
**Sugestão**: ter os dois estilos (para o 3.4 e para o 3.10), e no código fazer o check da versão para saber qual usar.

**Comment by dinizime** [comment]
3.10 se torna LTR semana que vem. Não daremos suporte ao QGIS 3.4

**Comment by JoaoFelipeAGuimaraes** [comment]
o problema no 3.10.2 é da versão em si, na dev 3.11 e na 3.10.2-2 (com splash LTR) funciona

**Comment by JoaoFelipeAGuimaraes** [comment]
conversão completa, estilos e svgs agora embutidos no .sqlite, pasta de simbologia mantida para referencia apenas.
