### ISSUE TITLE
Criação de pontos por azimute/distância - Implementar

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#23]
Criar ferramenta que permita ao usuário criar um novo ponto a partir de um azimute/distância, partindo-se de um ponto previamente selecionado.

Útil para o lançamento de alvos de artilharia a partir de uma posição conhecida (de peça de artilharia ou de tropa).

**Comment by JoaoFelipeAGuimaraes** [comment]
Adicionado, permite criação de pontos a partir da seleção de ponto já existente, azimute e distância
