### ISSUE TITLE
Sombreamento do terreno

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#25]
Recuperar informação de azimute/declinação do Sol ou da Lua (Suncalc.org e Mooncalc.org) e gerar raster de sombreamento sobre DEM. Usuário deve informar, em um diálogo, a data e a hora que deseja estimar a iluminação do terreno.

**Sugestão de implementação**
- Gerar link do Suncalc.org ou do Mooncalc.org conforme [API](https://www.torsten-hoffmann.de/apis/suncalcmooncalc/link_en.html)
- Usar _requests_ e _BeautifulSoup_ para recuperar os valores das tags _sunhoehe_ (declinação) e _azimuth_ (azimute)
- Gerar o sombreamento utilizando o comando [deste link](https://docs.qgis.org/2.8/en/docs/user_manual/processing_algs/gdalogr/gdal_analysis/hillshade.html).

**Comment by JoaoFelipeAGuimaraes** [comment]
Adicionada funcionalidade de sombreamento de terreno com base na posição, data e hora com base na posição do Sol
