### ISSUE TITLE
Calculadora de coordenadas - Problema com camadas de nomes iguais

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#6]
Quando o usuário possui camadas com nomes iguais, não se tem como saber qual se está selecionando na ferramenta. Em testes com dois SQLite de simbologia, a ferramenta sequer abriu.

Corrigir.

**Comment by dinizime** [comment]
Verificar se ainda procede @JoaoFelipeAGuimaraes .

**Comment by diegobenincasa** [comment]
O bug da ferramenta não abrir não acontece mais, até porque a lógica foi trocada pelo @JoaoFelipeAGuimaraes (e ficou melhor do que antes). Mas continua a situação das camadas com nomes iguais: é impossível diferenciar as mesmas apenas pelo nome.

Como a ferramenta funciona, vou atualizar para "Enhancement".

**Comment by JoaoFelipeAGuimaraes** [comment]
Resolvido no último commit, agora aparece "nome do arquivo\nome da camada"
