### ISSUE TITLE
Localizar carta - Problema ao fechar QGIS

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#7]
QGIS gera minidump ao ser encerrado após a ferramenta ter sido utilizada. Provavelmente o problema está no setMapTool e unsetMapTool.

Corrigir.

**Comment by dinizime** [comment]
Verificar se ainda procede @JoaoFelipeAGuimaraes .

**Comment by JoaoFelipeAGuimaraes** [comment]
Não ocorre com a nova versão
