### ISSUE TITLE
Localizar carta - Localiza fora do BR

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#8]
Seleção por box ou geometria está buscando cartas fora do Brasil. Ocorre porque a ferramenta calcula a carta 1:100k e, existindo o MI, estende a nomenclatura até a 1:25k, o que pode prever cartas inexistentes.

Talvez o cálculo de 1:50k e 1:25k esteja incorreto.

Verificar e corrigir.

**Comment by dinizime** [comment]
Verificar se ainda procede @JoaoFelipeAGuimaraes .

**Comment by JoaoFelipeAGuimaraes** [comment]
Nova ferramenta de busca indica quando o ponto, area selecionada está fora do país

**Comment by dinizime** [comment]
Excelente.
