### ISSUE TITLE
Trafegabilidade - Implementar

### ISSUE THREAD

**Issue by diegobenincasa** [dsgoficial/DSGToolsOp#9]
Criar ferramenta de confecção de mapas de restrição de movimento.

Aspectos:
- Ler DEM
- Gerar declividade
- Classificar declividade a partir de seleção de meio de deslocamento
- Solicitar camadas restritivas (opcional): vegetação e hidrografia

**Comment by JoaoFelipeAGuimaraes** [comment]
adicionado
